---
- name: Debian | Supported OS
  set_fact:
    holland_supported_os: True

- name: Debian | setup holland apt key
  apt_key: url='http://download.opensuse.org/repositories/home:/holland-backup/xUbuntu_14.04/Release.key' state=present

- name: Debian | setup holland apt repository
  apt_repository: repo='deb http://download.opensuse.org/repositories/home:/holland-backup/xUbuntu_14.04/ ./' state=present
