---
# tasks file for holland
- name: setup holland apt key
  apt_key: url='http://download.opensuse.org/repositories/home:/holland-backup/xUbuntu_14.04/Release.key' state=present

- name: setup holland apt repository
  apt_repository: repo='deb http://download.opensuse.org/repositories/home:/holland-backup/xUbuntu_14.04/ ./' state=present

- name: install holland
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=86400
  with_items:
    - holland
    - holland-mysqldump
