---
# tasks file for holland
- include: Debian.yml
  when: ansible_os_family == 'Debian'

- include: RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: unsupported_os.yml
  when: holland_supported_os is not defined

- name: check cron setup status
  stat: path=/etc/cron.d/holland
  register: cron_setup

- name: setup nightly backups with cron
  template: src=holland.j2 dest=/etc/cron.d/holland owner=root group=root mode=0644
  when: cron_setup.stat.exists == False
